// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Confirmar struct {
	Flag                 int32    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirmar) Reset()         { *m = Confirmar{} }
func (m *Confirmar) String() string { return proto.CompactTextString(m) }
func (*Confirmar) ProtoMessage()    {}
func (*Confirmar) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Confirmar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmar.Unmarshal(m, b)
}
func (m *Confirmar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmar.Marshal(b, m, deterministic)
}
func (m *Confirmar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmar.Merge(m, src)
}
func (m *Confirmar) XXX_Size() int {
	return xxx_messageInfo_Confirmar.Size(m)
}
func (m *Confirmar) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmar.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmar proto.InternalMessageInfo

func (m *Confirmar) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

// 1 = muerto, 0 = infectado
type Opcion struct {
	Flag                 int32    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opcion) Reset()         { *m = Opcion{} }
func (m *Opcion) String() string { return proto.CompactTextString(m) }
func (*Opcion) ProtoMessage()    {}
func (*Opcion) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Opcion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opcion.Unmarshal(m, b)
}
func (m *Opcion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opcion.Marshal(b, m, deterministic)
}
func (m *Opcion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opcion.Merge(m, src)
}
func (m *Opcion) XXX_Size() int {
	return xxx_messageInfo_Opcion.Size(m)
}
func (m *Opcion) XXX_DiscardUnknown() {
	xxx_messageInfo_Opcion.DiscardUnknown(m)
}

var xxx_messageInfo_Opcion proto.InternalMessageInfo

func (m *Opcion) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type Nombre struct {
	Nombre               string   `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nombre) Reset()         { *m = Nombre{} }
func (m *Nombre) String() string { return proto.CompactTextString(m) }
func (*Nombre) ProtoMessage()    {}
func (*Nombre) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Nombre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nombre.Unmarshal(m, b)
}
func (m *Nombre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nombre.Marshal(b, m, deterministic)
}
func (m *Nombre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nombre.Merge(m, src)
}
func (m *Nombre) XXX_Size() int {
	return xxx_messageInfo_Nombre.Size(m)
}
func (m *Nombre) XXX_DiscardUnknown() {
	xxx_messageInfo_Nombre.DiscardUnknown(m)
}

var xxx_messageInfo_Nombre proto.InternalMessageInfo

func (m *Nombre) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

type Identificador struct {
	Identificador        int32    `protobuf:"varint,1,opt,name=identificador,proto3" json:"identificador,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identificador) Reset()         { *m = Identificador{} }
func (m *Identificador) String() string { return proto.CompactTextString(m) }
func (*Identificador) ProtoMessage()    {}
func (*Identificador) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Identificador) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identificador.Unmarshal(m, b)
}
func (m *Identificador) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identificador.Marshal(b, m, deterministic)
}
func (m *Identificador) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identificador.Merge(m, src)
}
func (m *Identificador) XXX_Size() int {
	return xxx_messageInfo_Identificador.Size(m)
}
func (m *Identificador) XXX_DiscardUnknown() {
	xxx_messageInfo_Identificador.DiscardUnknown(m)
}

var xxx_messageInfo_Identificador proto.InternalMessageInfo

func (m *Identificador) GetIdentificador() int32 {
	if m != nil {
		return m.Identificador
	}
	return 0
}

type TuplaId struct {
	Identificador        int32    `protobuf:"varint,1,opt,name=identificador,proto3" json:"identificador,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TuplaId) Reset()         { *m = TuplaId{} }
func (m *TuplaId) String() string { return proto.CompactTextString(m) }
func (*TuplaId) ProtoMessage()    {}
func (*TuplaId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *TuplaId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TuplaId.Unmarshal(m, b)
}
func (m *TuplaId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TuplaId.Marshal(b, m, deterministic)
}
func (m *TuplaId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TuplaId.Merge(m, src)
}
func (m *TuplaId) XXX_Size() int {
	return xxx_messageInfo_TuplaId.Size(m)
}
func (m *TuplaId) XXX_DiscardUnknown() {
	xxx_messageInfo_TuplaId.DiscardUnknown(m)
}

var xxx_messageInfo_TuplaId proto.InternalMessageInfo

func (m *TuplaId) GetIdentificador() int32 {
	if m != nil {
		return m.Identificador
	}
	return 0
}

func (m *TuplaId) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func init() {
	proto.RegisterType((*Confirmar)(nil), "Confirmar")
	proto.RegisterType((*Opcion)(nil), "Opcion")
	proto.RegisterType((*Nombre)(nil), "Nombre")
	proto.RegisterType((*Identificador)(nil), "Identificador")
	proto.RegisterType((*TuplaId)(nil), "TuplaId")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x5b, 0xd1, 0xa4, 0x1d, 0x4d, 0xab, 0x7b, 0x10, 0x29, 0x82, 0x65, 0xb1, 0xe0, 0x41,
	0x56, 0xa9, 0xf8, 0x01, 0xfc, 0x03, 0x92, 0x43, 0x5b, 0x69, 0x3c, 0xe9, 0x41, 0xb6, 0xd9, 0x4d,
	0x18, 0x48, 0x76, 0xc2, 0x26, 0xfa, 0xf9, 0x85, 0x4d, 0x1a, 0x52, 0xf1, 0xe0, 0xed, 0xed, 0x1b,
	0x66, 0x7e, 0xb3, 0x6f, 0x60, 0x94, 0xeb, 0xb2, 0x94, 0xa9, 0x2e, 0x45, 0x61, 0xa9, 0x22, 0x7e,
	0x01, 0xc3, 0x27, 0x32, 0x09, 0xda, 0x5c, 0x5a, 0xc6, 0x60, 0x3f, 0xc9, 0x64, 0x7a, 0xd6, 0x9f,
	0xf6, 0xaf, 0x0e, 0xd6, 0x4e, 0xf3, 0x73, 0xf0, 0x56, 0x45, 0x8c, 0x64, 0xfe, 0xac, 0x4e, 0xc1,
	0x5b, 0x52, 0xbe, 0xb1, 0x9a, 0x9d, 0x82, 0x67, 0x9c, 0x72, 0xf5, 0xe1, 0xba, 0x79, 0xf1, 0x7b,
	0x08, 0x42, 0xa5, 0x4d, 0x85, 0x09, 0xc6, 0x52, 0x91, 0x65, 0x97, 0x10, 0x60, 0xd7, 0x68, 0xe6,
	0xed, 0x9a, 0xfc, 0x05, 0xfc, 0xb7, 0xaf, 0x22, 0x93, 0xa1, 0xfa, 0x5f, 0x43, 0x87, 0xbf, 0xd7,
	0xe5, 0xcf, 0x3f, 0xe0, 0x70, 0xb5, 0x88, 0x3e, 0x23, 0x6d, 0xbf, 0x31, 0xd6, 0x6c, 0x06, 0x47,
	0x0b, 0x69, 0x94, 0xb4, 0xcd, 0xda, 0xbe, 0xa8, 0xc5, 0x04, 0x44, 0x9b, 0x03, 0xef, 0xb1, 0x19,
	0x04, 0xaf, 0x5a, 0xa1, 0x7d, 0x48, 0x32, 0x4c, 0x51, 0x11, 0xf3, 0x45, 0x9d, 0xc2, 0x64, 0xdb,
	0xc0, 0x7b, 0xb7, 0xfd, 0xb9, 0x82, 0xe3, 0x67, 0x59, 0xc9, 0x25, 0x29, 0xdd, 0x12, 0x38, 0x0c,
	0x6a, 0x42, 0xa8, 0xd8, 0x40, 0x34, 0x9f, 0xf8, 0x35, 0xfe, 0x1a, 0xc6, 0x11, 0x65, 0x18, 0x63,
	0xd5, 0x2e, 0x32, 0x12, 0x3b, 0x31, 0x75, 0x38, 0x8f, 0x27, 0xef, 0x63, 0x77, 0xac, 0xf2, 0x66,
	0x7b, 0xbc, 0x8d, 0xe7, 0x8c, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x4b, 0x24, 0xd1,
	0xcf, 0x01, 0x00, 0x00,
}
