// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoslab3/messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comando struct {
	Accion               string   `protobuf:"bytes,1,opt,name=accion,proto3" json:"accion,omitempty"`
	Sector               string   `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Base                 string   `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Valor                string   `protobuf:"bytes,4,opt,name=valor,proto3" json:"valor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comando) Reset()         { *m = Comando{} }
func (m *Comando) String() string { return proto.CompactTextString(m) }
func (*Comando) ProtoMessage()    {}
func (*Comando) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{0}
}

func (m *Comando) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comando.Unmarshal(m, b)
}
func (m *Comando) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comando.Marshal(b, m, deterministic)
}
func (m *Comando) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comando.Merge(m, src)
}
func (m *Comando) XXX_Size() int {
	return xxx_messageInfo_Comando.Size(m)
}
func (m *Comando) XXX_DiscardUnknown() {
	xxx_messageInfo_Comando.DiscardUnknown(m)
}

var xxx_messageInfo_Comando proto.InternalMessageInfo

func (m *Comando) GetAccion() string {
	if m != nil {
		return m.Accion
	}
	return ""
}

func (m *Comando) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Comando) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Comando) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

type Direccion struct {
	Direccion            string   `protobuf:"bytes,1,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Fulcrum              string   `protobuf:"bytes,2,opt,name=fulcrum,proto3" json:"fulcrum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Direccion) Reset()         { *m = Direccion{} }
func (m *Direccion) String() string { return proto.CompactTextString(m) }
func (*Direccion) ProtoMessage()    {}
func (*Direccion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{1}
}

func (m *Direccion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direccion.Unmarshal(m, b)
}
func (m *Direccion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direccion.Marshal(b, m, deterministic)
}
func (m *Direccion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direccion.Merge(m, src)
}
func (m *Direccion) XXX_Size() int {
	return xxx_messageInfo_Direccion.Size(m)
}
func (m *Direccion) XXX_DiscardUnknown() {
	xxx_messageInfo_Direccion.DiscardUnknown(m)
}

var xxx_messageInfo_Direccion proto.InternalMessageInfo

func (m *Direccion) GetDireccion() string {
	if m != nil {
		return m.Direccion
	}
	return ""
}

func (m *Direccion) GetFulcrum() string {
	if m != nil {
		return m.Fulcrum
	}
	return ""
}

type Vector struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{2}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Vector) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Vector) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

type Sector struct {
	Sector               string   `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sector) Reset()         { *m = Sector{} }
func (m *Sector) String() string { return proto.CompactTextString(m) }
func (*Sector) ProtoMessage()    {}
func (*Sector) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{3}
}

func (m *Sector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sector.Unmarshal(m, b)
}
func (m *Sector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sector.Marshal(b, m, deterministic)
}
func (m *Sector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sector.Merge(m, src)
}
func (m *Sector) XXX_Size() int {
	return xxx_messageInfo_Sector.Size(m)
}
func (m *Sector) XXX_DiscardUnknown() {
	xxx_messageInfo_Sector.DiscardUnknown(m)
}

var xxx_messageInfo_Sector proto.InternalMessageInfo

func (m *Sector) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

type Base struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base) Reset()         { *m = Base{} }
func (m *Base) String() string { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()    {}
func (*Base) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{4}
}

func (m *Base) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base.Unmarshal(m, b)
}
func (m *Base) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base.Marshal(b, m, deterministic)
}
func (m *Base) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base.Merge(m, src)
}
func (m *Base) XXX_Size() int {
	return xxx_messageInfo_Base.Size(m)
}
func (m *Base) XXX_DiscardUnknown() {
	xxx_messageInfo_Base.DiscardUnknown(m)
}

var xxx_messageInfo_Base proto.InternalMessageInfo

func (m *Base) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

type Confirmar struct {
	Flag                 string   `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirmar) Reset()         { *m = Confirmar{} }
func (m *Confirmar) String() string { return proto.CompactTextString(m) }
func (*Confirmar) ProtoMessage()    {}
func (*Confirmar) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{5}
}

func (m *Confirmar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmar.Unmarshal(m, b)
}
func (m *Confirmar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmar.Marshal(b, m, deterministic)
}
func (m *Confirmar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmar.Merge(m, src)
}
func (m *Confirmar) XXX_Size() int {
	return xxx_messageInfo_Confirmar.Size(m)
}
func (m *Confirmar) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmar.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmar proto.InternalMessageInfo

func (m *Confirmar) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type Soldados struct {
	Sector               string   `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Soldados) Reset()         { *m = Soldados{} }
func (m *Soldados) String() string { return proto.CompactTextString(m) }
func (*Soldados) ProtoMessage()    {}
func (*Soldados) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{6}
}

func (m *Soldados) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Soldados.Unmarshal(m, b)
}
func (m *Soldados) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Soldados.Marshal(b, m, deterministic)
}
func (m *Soldados) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Soldados.Merge(m, src)
}
func (m *Soldados) XXX_Size() int {
	return xxx_messageInfo_Soldados.Size(m)
}
func (m *Soldados) XXX_DiscardUnknown() {
	xxx_messageInfo_Soldados.DiscardUnknown(m)
}

var xxx_messageInfo_Soldados proto.InternalMessageInfo

func (m *Soldados) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Soldados) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

type Numero struct {
	Numero               string   `protobuf:"bytes,1,opt,name=numero,proto3" json:"numero,omitempty"`
	X                    string   `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,4,opt,name=z,proto3" json:"z,omitempty"`
	Fulcrum              string   `protobuf:"bytes,5,opt,name=fulcrum,proto3" json:"fulcrum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Numero) Reset()         { *m = Numero{} }
func (m *Numero) String() string { return proto.CompactTextString(m) }
func (*Numero) ProtoMessage()    {}
func (*Numero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{7}
}

func (m *Numero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Numero.Unmarshal(m, b)
}
func (m *Numero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Numero.Marshal(b, m, deterministic)
}
func (m *Numero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Numero.Merge(m, src)
}
func (m *Numero) XXX_Size() int {
	return xxx_messageInfo_Numero.Size(m)
}
func (m *Numero) XXX_DiscardUnknown() {
	xxx_messageInfo_Numero.DiscardUnknown(m)
}

var xxx_messageInfo_Numero proto.InternalMessageInfo

func (m *Numero) GetNumero() string {
	if m != nil {
		return m.Numero
	}
	return ""
}

func (m *Numero) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Numero) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Numero) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

func (m *Numero) GetFulcrum() string {
	if m != nil {
		return m.Fulcrum
	}
	return ""
}

type Cambio struct {
	Nombre               string   `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tiempo1              string   `protobuf:"bytes,2,opt,name=tiempo1,proto3" json:"tiempo1,omitempty"`
	Valor                string   `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tiempo2              string   `protobuf:"bytes,4,opt,name=tiempo2,proto3" json:"tiempo2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cambio) Reset()         { *m = Cambio{} }
func (m *Cambio) String() string { return proto.CompactTextString(m) }
func (*Cambio) ProtoMessage()    {}
func (*Cambio) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{8}
}

func (m *Cambio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cambio.Unmarshal(m, b)
}
func (m *Cambio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cambio.Marshal(b, m, deterministic)
}
func (m *Cambio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cambio.Merge(m, src)
}
func (m *Cambio) XXX_Size() int {
	return xxx_messageInfo_Cambio.Size(m)
}
func (m *Cambio) XXX_DiscardUnknown() {
	xxx_messageInfo_Cambio.DiscardUnknown(m)
}

var xxx_messageInfo_Cambio proto.InternalMessageInfo

func (m *Cambio) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Cambio) GetTiempo1() string {
	if m != nil {
		return m.Tiempo1
	}
	return ""
}

func (m *Cambio) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

func (m *Cambio) GetTiempo2() string {
	if m != nil {
		return m.Tiempo2
	}
	return ""
}

type SectorVector struct {
	Sector               string   `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	X                    string   `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SectorVector) Reset()         { *m = SectorVector{} }
func (m *SectorVector) String() string { return proto.CompactTextString(m) }
func (*SectorVector) ProtoMessage()    {}
func (*SectorVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{9}
}

func (m *SectorVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectorVector.Unmarshal(m, b)
}
func (m *SectorVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectorVector.Marshal(b, m, deterministic)
}
func (m *SectorVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectorVector.Merge(m, src)
}
func (m *SectorVector) XXX_Size() int {
	return xxx_messageInfo_SectorVector.Size(m)
}
func (m *SectorVector) XXX_DiscardUnknown() {
	xxx_messageInfo_SectorVector.DiscardUnknown(m)
}

var xxx_messageInfo_SectorVector proto.InternalMessageInfo

func (m *SectorVector) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *SectorVector) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *SectorVector) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *SectorVector) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

type Log struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Valor                string   `protobuf:"bytes,2,opt,name=valor,proto3" json:"valor,omitempty"`
	Tiempo               string   `protobuf:"bytes,3,opt,name=tiempo,proto3" json:"tiempo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2e02856b5ed9737, []int{10}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Log) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

func (m *Log) GetTiempo() string {
	if m != nil {
		return m.Tiempo
	}
	return ""
}

func init() {
	proto.RegisterType((*Comando)(nil), "Comando")
	proto.RegisterType((*Direccion)(nil), "Direccion")
	proto.RegisterType((*Vector)(nil), "Vector")
	proto.RegisterType((*Sector)(nil), "Sector")
	proto.RegisterType((*Base)(nil), "Base")
	proto.RegisterType((*Confirmar)(nil), "Confirmar")
	proto.RegisterType((*Soldados)(nil), "Soldados")
	proto.RegisterType((*Numero)(nil), "Numero")
	proto.RegisterType((*Cambio)(nil), "Cambio")
	proto.RegisterType((*SectorVector)(nil), "SectorVector")
	proto.RegisterType((*Log)(nil), "Log")
}

func init() { proto.RegisterFile("protoslab3/messages.proto", fileDescriptor_d2e02856b5ed9737) }

var fileDescriptor_d2e02856b5ed9737 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x4f, 0xda, 0x2e, 0x59, 0x6e, 0x63, 0x05, 0x83, 0xa6, 0x12, 0x81, 0x18, 0x1e, 0x08, 0xa4,
	0x09, 0x23, 0x3a, 0x89, 0x0f, 0xd0, 0x22, 0x26, 0xa4, 0x81, 0xa6, 0x55, 0xec, 0x81, 0x17, 0xe4,
	0x26, 0x6e, 0x15, 0x48, 0xe2, 0xc9, 0x49, 0xa7, 0x6d, 0xaf, 0x7c, 0x33, 0x3e, 0x19, 0x8a, 0xcf,
	0x4e, 0x5c, 0x04, 0xa8, 0x3c, 0xd5, 0xbf, 0xeb, 0xf9, 0x7e, 0x7f, 0x2e, 0x09, 0x3c, 0xbc, 0x54,
	0xb2, 0x96, 0x55, 0xce, 0xe7, 0xc7, 0xaf, 0x0b, 0x51, 0x55, 0x7c, 0x29, 0x2a, 0xa6, 0x6b, 0x34,
	0x81, 0x70, 0x2a, 0x0b, 0x5e, 0xa6, 0x92, 0xec, 0x43, 0xc0, 0x93, 0x24, 0x93, 0xe5, 0xc8, 0x3f,
	0xf0, 0x5f, 0x46, 0xe7, 0x06, 0x35, 0xf5, 0x4a, 0x24, 0xb5, 0x54, 0xa3, 0x1e, 0xd6, 0x11, 0x11,
	0x02, 0x83, 0x39, 0xaf, 0xc4, 0xa8, 0xaf, 0xab, 0xfa, 0x4c, 0x1e, 0xc0, 0xd6, 0x15, 0xcf, 0xa5,
	0x1a, 0x0d, 0x74, 0x11, 0x01, 0x9d, 0x42, 0xf4, 0x2e, 0x53, 0x02, 0xc7, 0x3d, 0x82, 0x28, 0xb5,
	0xc0, 0x30, 0x75, 0x05, 0x32, 0x82, 0x70, 0xb1, 0xca, 0x13, 0xb5, 0x2a, 0x0c, 0x9b, 0x85, 0x74,
	0x0c, 0xc1, 0x05, 0x12, 0xef, 0x82, 0x7f, 0x6d, 0x6e, 0xfa, 0xd7, 0x0d, 0xba, 0x31, 0xbd, 0xfe,
	0x4d, 0x83, 0x6e, 0x8d, 0x22, 0xff, 0x96, 0x1e, 0x40, 0x30, 0xc3, 0x3b, 0x9d, 0x09, 0xdf, 0x35,
	0x41, 0x63, 0x18, 0x4c, 0x1a, 0xe1, 0xd6, 0x8c, 0xdf, 0x99, 0xa1, 0x4f, 0x20, 0x9a, 0xca, 0x72,
	0x91, 0xa9, 0x82, 0x6b, 0xb7, 0x8b, 0x9c, 0x2f, 0x6d, 0x43, 0x73, 0xa6, 0x6f, 0x61, 0x7b, 0x26,
	0xf3, 0x94, 0xa7, 0xb2, 0xfa, 0x1b, 0x41, 0x3b, 0xb8, 0xe7, 0x0c, 0x4e, 0x21, 0xf8, 0xb4, 0x2a,
	0x84, 0xd2, 0x99, 0x97, 0xfa, 0x64, 0x6f, 0x21, 0x42, 0x8b, 0xbd, 0x35, 0x8b, 0xfd, 0x35, 0x8b,
	0x03, 0x63, 0xd1, 0x0d, 0x6c, 0x6b, 0x3d, 0xb0, 0x6f, 0x10, 0x4c, 0x79, 0x31, 0xcf, 0x90, 0x45,
	0x16, 0x73, 0x25, 0x5a, 0x16, 0x8d, 0x9a, 0xbb, 0x75, 0x26, 0x8a, 0x4b, 0xf9, 0xc6, 0x86, 0x6d,
	0x60, 0xb7, 0xc7, 0xbe, 0xb3, 0xc7, 0xae, 0x7f, 0x6c, 0xf8, 0x2d, 0xa4, 0x67, 0xb0, 0x8b, 0x41,
	0x5f, 0xfc, 0x33, 0xee, 0xcd, 0x7d, 0xd1, 0x13, 0xe8, 0x9f, 0xca, 0xe5, 0x9f, 0xf6, 0xd2, 0x89,
	0xeb, 0xb9, 0xe2, 0xf6, 0x21, 0x40, 0x35, 0x66, 0xa2, 0x41, 0xe3, 0x1f, 0x3e, 0xec, 0x4d, 0x94,
	0xfc, 0x2e, 0xd4, 0xd7, 0x99, 0x50, 0x57, 0x59, 0x22, 0xc8, 0x21, 0xec, 0x7e, 0xe4, 0x65, 0xca,
	0x95, 0xc9, 0x67, 0x9b, 0x99, 0x77, 0x20, 0x0e, 0x19, 0x1a, 0xa0, 0x1e, 0x39, 0x84, 0x9d, 0x13,
	0x51, 0xb7, 0xfb, 0x8d, 0x98, 0x3d, 0xc6, 0x21, 0xc3, 0xed, 0x51, 0x8f, 0xbc, 0x80, 0xbd, 0x0f,
	0x65, 0x22, 0xcb, 0x2a, 0xab, 0x6a, 0x51, 0x26, 0x19, 0x27, 0x21, 0xc3, 0x20, 0x62, 0x60, 0xed,
	0xc3, 0x43, 0xbd, 0xf1, 0xcf, 0x3e, 0x0c, 0xdf, 0xe3, 0x62, 0xfe, 0x4f, 0xc6, 0xa6, 0x0c, 0xe4,
	0x29, 0xec, 0x9c, 0x89, 0x34, 0xb3, 0x1b, 0x68, 0xbb, 0x9c, 0x59, 0x47, 0x96, 0xd0, 0xf4, 0xdc,
	0x61, 0xee, 0xd2, 0x7e, 0x9b, 0xf7, 0x18, 0x22, 0x3d, 0x4f, 0xbf, 0x1e, 0x5b, 0xac, 0xf9, 0x89,
	0x43, 0x86, 0x52, 0xa9, 0x47, 0x5e, 0xc1, 0x7d, 0x57, 0xbc, 0xf1, 0xe6, 0x78, 0x58, 0x9f, 0xb6,
	0x51, 0x9a, 0x47, 0x40, 0x26, 0xab, 0x2a, 0xe1, 0x0a, 0x65, 0x9d, 0x8b, 0x42, 0xd6, 0x92, 0x38,
	0x83, 0x62, 0xeb, 0x8a, 0x7a, 0xe4, 0x19, 0xdc, 0xc5, 0xe6, 0x46, 0x99, 0x69, 0x6d, 0x4d, 0xa3,
	0x5e, 0xdd, 0x35, 0xc4, 0xae, 0xcf, 0x79, 0x9d, 0x15, 0xb2, 0x79, 0xa4, 0x1c, 0xee, 0x01, 0x3b,
	0x95, 0x4b, 0xea, 0x91, 0xe7, 0x10, 0x4d, 0xa4, 0x52, 0x5c, 0x35, 0xff, 0xbb, 0x7c, 0x6b, 0x26,
	0x26, 0xf7, 0xbe, 0x0c, 0xf1, 0x4b, 0xda, 0x7e, 0x45, 0xe7, 0x81, 0x2e, 0x1c, 0xff, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x57, 0xf6, 0x33, 0xe6, 0x63, 0x05, 0x00, 0x00,
}
